# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  

permissions:
  contents: read

jobs:
  build-n-publish:

    runs-on: ubuntu-latest
    env:
      ## Possible options are deploy/ update/ schedule/ unschedule/ status
      action: unschedule
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest 
        python -m venv env
        source env/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: set the AWS creds
      
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        action: update

    - name: deploy to AWS serverless Arch
      run: |
        source env/bin/activate
        pip freeze
        zappa $action stage

        
        


    
